[tools]
terraform = "latest"
usage = "latest"
packer = "latest"
kops = "latest"
helm = "latest"
boundary = "latest"
waypoint = "latest"
bazel = "latest"
protoc = "latest"
awscli = "latest"
meson = "latest"
k9s = "latest"
jq = "latest"
bat-extras = "latest"
bat = "latest"
loki-logcli = "3.6.7"
buf = "latest"
doctl = "latest"
promtool = "3.10.0"
uv = "latest"
fzf = "latest"
zoxide = "latest"
lazygit = "latest"
zellij = "latest"
starship = "latest"
zola = "latest"
helix = "latest"
neovim = "latest"
node = "latest"
mdbook = "latest"
ripgrep = "latest"
jless = "latest"
sccache = "latest"
just = "latest"
ruby = "latest"
java = "latest"
gradle = "latest"
sbt = "latest"
scala = "latest"
kotlin = "latest"
spring-boot = "latest"
spark = "latest"
maven = "latest"
kscript = "latest"
ki = "latest"
mprocs = "latest"
go = "latest"
watchexec = "latest"
zig = "latest"
zls = "latest"
"cargo:bacon" = { version = "latest", features = "clipboard sound" }
sops = "latest"
"cargo:rops-cli" = "latest"
"ubi:bits-n-bites/buildcache" = { version = "latest", provider = "gitlab" }
yt-dlp = "latest"
ansible = "latest"
azure = "latest"
azure-kubelogin = "latest"
kubectl = "latest"
"cargo:zbus_xmlgen" = "latest"
"cargo:tomlq" = "latest"
"cargo:lucky_commit" = "latest"
"cargo:wild-linker" = "latest"
cilium-cli = "latest"
"cargo:tuckr" = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["rust"]
